/alpha/ping360_node:
  ros__parameters:
    # Note: USB device name
    device: "/dev/ttyUSB0"
    # Note: baudarate of serial device
    baudrate: 115200
    # Note: Emulates a sonar if Ping360 cannot be initialized
    fallback_emulated: true
    #If serial, use "serial", elif ethernet, "udp"
    connection_type: "udp"
    udp_address: "0.0.0.0"
    udp_port: 12345
    #Frame ID for msgs
    frame: ping360_sonar_link
    #Sonar gain (0 = low, 1 = normal, 2 = high)"
    gain: 0
    #Sonar operating frequency [kHz]" [650-850]
    frequency: 740
    #Sonar max range [m] [1-50]"
    range_max: 50
    # Scanned angular sector around sonar heading [degrees]. Will oscillate if not 360
    angle_sector: 360
    custom_enabled: true
    angle_min: 0
    angle_max: 180
    slice: true
    min_angle: 90
    # Sonar angular resolution [degrees] [0-20]
    angle_step: 1
    # "Output image size [pixels]"
    image_size: 300
    # Intensity threshold for LaserScan message
    scan_threshold: 200
    # Speed of sound [m/s]
    speed_of_sound: 1500
    # Image publishing rate [ms]
    image_rate: 100
    # Sonar timeout [ms]
    sonar_timeout: 2000
    # Bools for topics
    publish_image: true
    publish_scan: true
    publish_echo: true
    publish_pcl: true
