/alpha/ping360_node:
  ros__parameters:
    device: "/dev/ttyUSB0"
    baudrate: 115200
    fallback_emulated: true
    connection_type: "udp"
    udp_address: "0.0.0.0"
    udp_port: 12345
    frame: ping360_sonar_link
    #Sonar gain (0 = low, 1 = normal, 2 = high)"
    gain: 0
    #Sonar operating frequency [kHz]" [650-850]
    frequency: 740
    #Sonar max range [m] [1-50]"
    range_max: 2
    # Scanned angular sector around sonar heading [degrees]. Will oscillate if not 360
    angle_sector: 360
    # Sonar angular resolution [degrees] [0-20]
    angle_step: 1
    # "Output image size [pixels]"
    image_size: 300
    # Intensity threshold for LaserScan message
    scan_threshold: 200
    # Speed of sound [m/s]
    speed_of_sound: 1500
    # Image publishing rate [ms]
    image_rate: 100
    # Sonar timeout [ms]
    sonar_timeout: 2000
    publish_image: true
    publish_scan: true
    publish_echo: true
